# Generated by Django 3.2 on 2022-05-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resimg',
            name='title',
            field=models.CharField(default='mk', max_length=345),
            preserve_default=False,
        ),
    ]
