# Generated by Django 3.2 on 2022-05-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0002_resimg_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resimg',
            name='title',
        ),
        migrations.AlterField(
            model_name='resimg',
            name='img',
            field=models.ImageField(blank=True, upload_to='PANDEMIC/Recources'),
        ),
        migrations.AlterField(
            model_name='resimg',
            name='img1',
            field=models.ImageField(blank=True, upload_to='PANDEMIC/Recources'),
        ),
        migrations.AlterField(
            model_name='resimg',
            name='img2',
            field=models.ImageField(blank=True, upload_to='PANDEMIC/Recources'),
        ),
        migrations.AlterField(
            model_name='resimg',
            name='img3',
            field=models.ImageField(blank=True, upload_to='PANDEMIC/Recources'),
        ),
    ]
