# Generated by Django 3.2 on 2022-05-31 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0003_auto_20220531_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='sub_text',
        ),
    ]
