# Generated by Django 3.2 on 2022-05-31 08:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0004_remove_blog_sub_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='sub_text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
