# Generated by Django 3.2 on 2022-05-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0005_blog_sub_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='sub_text',
            field=models.TextField(blank=True),
        ),
    ]
