# Generated by Django 3.2 on 2022-06-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0007_auto_20220604_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='img',
            field=models.ImageField(blank=True, upload_to='Testimony/img'),
        ),
    ]
