# Generated by Django 3.2 on 2022-06-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0009_res_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='res',
            name='url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
