# Generated by Django 3.2 on 2022-06-13 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0010_alter_res_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resimg',
            name='res',
        ),
        migrations.DeleteModel(
            name='Res',
        ),
        migrations.DeleteModel(
            name='ResImg',
        ),
    ]
