# Generated by Django 3.2 on 2022-06-13 09:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0011_auto_20220613_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=222)),
                ('img', models.ImageField(upload_to='Recources')),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('note', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'RESOURCES',
            },
        ),
        migrations.CreateModel(
            name='ResImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='PANDEMIC/Recources')),
                ('img1', models.ImageField(blank=True, upload_to='PANDEMIC/Recources')),
                ('img2', models.ImageField(blank=True, upload_to='PANDEMIC/Recources')),
                ('img3', models.ImageField(blank=True, upload_to='PANDEMIC/Recources')),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b.res')),
            ],
            options={
                'verbose_name_plural': 'RESOURCES IMAGES',
            },
        ),
    ]
